server:
  port: 8801

spring:
  application:
    name: config-server

  cloud:
    config:
      #下面配置为使用github仓库的配置文件,仓库中的配置文件会被转换成web接口，访问可以参照以下的规则：
      #/{application}/{profile}[/{label}]
      #/{application}-{profile}.yml
      #/{label}/{application}-{profile}.yml
      #/{application}-{profile}.properties
      #/{label}/{application}-{profile}.properties
      server:
        git:
          uri: https://github.com/JumpIntoMoon/springCloudConfig/
          searchPaths: respo
          username: t_yl@outlook.com
          password: tyltoto,.1
    bus:
      trace:
        enabled: true #跟踪总线事件
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#默认关闭了bus请求url，因此需要打开才能使用，下面为打开方式
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/